<?php
/**
 * @file
 * Module file for Drupal, required to be here.
 */

/**
 * Build callback for commerce_product_has_specified_terms on product.
 *
 * @param EntityDrupalWrapper $wrapper
 *   Wrapped entity type given by the rule.
 * @param array $terms
 *   Values for the condition settings.
 *
 * @return bool
 *   True is condition is valid. false otherwise.
 */
function commerce_product_display_has_specified_terms_build(EntityDrupalWrapper $wrapper, $terms) {
  $terms_to_check = array();
  foreach ($terms as $key => $target_id) {
    $terms_to_check[] = $target_id['target_id'];
  }

  // If commerce_product is attached.
  if (in_array('commerce_product', array_keys($wrapper->getPropertyInfo()))) {
    // Make sure we have a bridge to a display node.
    foreach ($wrapper->commerce_product->getPropertyInfo() as $field_name => $property) {

      if (isset($property['field']) && $property['field']['type'] == 'commerce_product_reference') {
        if ($wrapper->commerce_product->$field_name instanceof EntityListWrapper) {

          // Cycle through the product display reference to find term fields.
          foreach ($wrapper->commerce_product->$field_name as $node_display_wrapper) {
            foreach ($node_display_wrapper->getPropertyInfo() as $node_field_name => $node_property) {

              // Check if the property is of a taxonomy term type.
              if (isset($node_property['type']) && $node_property['type'] == 'taxonomy_term') {

                // If the wrapped field is an instance of EntityListWrapper class, that
                // means that field contains multiple values.
                if ($node_display_wrapper->$node_field_name instanceof EntityListWrapper) {
                  foreach ($node_display_wrapper->$node_field_name as $wrapper_term) {
                    // We have a match, apply discount
                    if (($key = array_search($wrapper_term->getIdentifier(), $terms_to_check)) !== FALSE) {
                      return TRUE;
                    }
                  }
                }
                elseif ($term =$node_display_wrapper->$node_field_name->value()) {
                  // The single value matches, return true.
                  if (($key = array_search($term->tid, $terms_to_check)) !== FALSE) {
                    return TRUE;
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  // Return false by default.
  return FALSE;
}
